# Site
name: "theJoshDean.com"
title: "JoshDean"
description: "Portfolio, experiments, things learned, and things that I'm learning!"
logo: 'assets/images/psccpicsquare.jpg'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-73531957-1'
disqus: 'joshdean'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  josh:
    name: 'Josh Dean'
    display_name: Josh
    gravatar: "d2206343fbd13e457e61a46b930629ac"
    email: josdea@gmail.com
    web: https://thejoshdean.com
    twitter: https://twitter.com/_DarkFlamingo
    description: "The more I learn the more my interests change. I've been learning more and more about Oracle SQL databses, javascript, and javascript frameworks like Vue.js and Vuetify."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, CNAME]
