baseURL = 'https://thejoshdean.com/'
languageCode = 'en-us'
title = 'Josh Dean'
theme = "anatole"
profilePicture = "images/profile.jpg"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "/portfolio/"
  weight = 3

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5


[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    shortname = '@josdea'