name: GitHub Pages - Hugo

on:
  push:
    branches:
      - hugo  # build when you push to the hugo branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Setup Dart Sass
        run: |
          wget -q https://github.com/sass/dart-sass/releases/download/1.83.1/dart-sass-1.83.1-linux-x64.tar.gz
          tar -xzf dart-sass-1.83.1-linux-x64.tar.gz
          sudo cp -r dart-sass/* /usr/local/bin/

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
